### ISSUE TITLE
Fennella - Fishing Guild Points NPC

### ISSUE THREAD

**Issue by ZamAnimal** [OmegaPrivateServer/issues#336]
## Summary

Talking to this NPC crashes the player and apparently the cluster
## Expected Behavior

Should give dialogue and a menu pop-up.
## Current Behavior

See Summary
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Zaminiel. I'm sure it'd behave this way for anyone though.
## Steps to Reproduce

1. Talk to Fennella in Port Windurst.
2. Disconnect because the cluster crashed.
3.
4.

**Comment by zierk** [comment]
Was fixed in emergency maintenance.

**Comment by GiggleCait** [comment]
Bhefhel Marlin, not able to turn in to Fishing Guild NPC for GP. I think this issue still persists unfortunately.
